// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace hololensMulti
{

using global::System;
using global::FlatBuffers;

public struct ObjectFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static ObjectFB GetRootAsObjectFB(ByteBuffer _bb) { return GetRootAsObjectFB(_bb, new ObjectFB()); }
  public static ObjectFB GetRootAsObjectFB(ByteBuffer _bb, ObjectFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ObjectFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ObjectID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ObjectType { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetObjectTypeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetObjectTypeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetObjectTypeArray() { return __p.__vector_as_array<byte>(6); }
  public byte OwnerID { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public hololensMulti.Vec3? Pos { get { int o = __p.__offset(10); return o != 0 ? (hololensMulti.Vec3?)(new hololensMulti.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public hololensMulti.Quat? Rot { get { int o = __p.__offset(12); return o != 0 ? (hololensMulti.Quat?)(new hololensMulti.Quat()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public hololensMulti.Vec3? Scale { get { int o = __p.__offset(14); return o != 0 ? (hololensMulti.Vec3?)(new hololensMulti.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartObjectFB(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddObjectID(FlatBufferBuilder builder, int ObjectID) { builder.AddInt(0, ObjectID, 0); }
  public static void AddObjectType(FlatBufferBuilder builder, StringOffset ObjectTypeOffset) { builder.AddOffset(1, ObjectTypeOffset.Value, 0); }
  public static void AddOwnerID(FlatBufferBuilder builder, byte OwnerID) { builder.AddByte(2, OwnerID, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<hololensMulti.Vec3> PosOffset) { builder.AddStruct(3, PosOffset.Value, 0); }
  public static void AddRot(FlatBufferBuilder builder, Offset<hololensMulti.Quat> RotOffset) { builder.AddStruct(4, RotOffset.Value, 0); }
  public static void AddScale(FlatBufferBuilder builder, Offset<hololensMulti.Vec3> ScaleOffset) { builder.AddStruct(5, ScaleOffset.Value, 0); }
  public static Offset<hololensMulti.ObjectFB> EndObjectFB(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<hololensMulti.ObjectFB>(o);
  }
  public static void FinishObjectFBBuffer(FlatBufferBuilder builder, Offset<hololensMulti.ObjectFB> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedObjectFBBuffer(FlatBufferBuilder builder, Offset<hololensMulti.ObjectFB> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
