// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace hololensMulti
{

using global::System;
using global::FlatBuffers;

public struct WelcomeFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static WelcomeFB GetRootAsWelcomeFB(ByteBuffer _bb) { return GetRootAsWelcomeFB(_bb, new WelcomeFB()); }
  public static WelcomeFB GetRootAsWelcomeFB(ByteBuffer _bb, WelcomeFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WelcomeFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte PlayerID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public string PlayerName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPlayerNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPlayerNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<hololensMulti.WelcomeFB> CreateWelcomeFB(FlatBufferBuilder builder,
      byte PlayerID = 0,
      StringOffset PlayerNameOffset = default(StringOffset)) {
    builder.StartTable(2);
    WelcomeFB.AddPlayerName(builder, PlayerNameOffset);
    WelcomeFB.AddPlayerID(builder, PlayerID);
    return WelcomeFB.EndWelcomeFB(builder);
  }

  public static void StartWelcomeFB(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayerID(FlatBufferBuilder builder, byte PlayerID) { builder.AddByte(0, PlayerID, 0); }
  public static void AddPlayerName(FlatBufferBuilder builder, StringOffset PlayerNameOffset) { builder.AddOffset(1, PlayerNameOffset.Value, 0); }
  public static Offset<hololensMulti.WelcomeFB> EndWelcomeFB(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<hololensMulti.WelcomeFB>(o);
  }
  public static void FinishWelcomeFBBuffer(FlatBufferBuilder builder, Offset<hololensMulti.WelcomeFB> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedWelcomeFBBuffer(FlatBufferBuilder builder, Offset<hololensMulti.WelcomeFB> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
